<?php 
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File accountactivate.php
 */
$premission =  new LiangLee_AccountDeactivate;
$user = get_input('user');
if($premission->elgg_is_account_deactive($user) || empty($user)){
	forward();		   
}

$submit = elgg_view('input/submit');
$form = elgg_view('input/text', array(
									  'name' => 'leeactivateaccount_code',
									  'value' => get_input('code')
									  ));
$user = elgg_view('input/hidden', array(
									  'name' => 'leeactivateaccount_user',
									  'value' => get_input('user')
									  ));
$lang1 =  elgg_echo('liang:lee:account:activate:1');

$html = <<<HTML
<div class="leeaccountactivate-activate">
      <div class="inner">
                  <h3> $lang1 </h3><br />
                    $form.$user <br />
					<div id="#wait">
                    $submit
					</div>
</div>
</div>
HTML;
echo $html;
?>