<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File sendactivation.php
 */
$submit = elgg_view('input/submit', array('value' => 'Get activation'));
$user = elgg_view('input/hidden', array(
									  'name' => 'leeactivateaccount_user',
									  'value' => get_input('user')
									  ));
$lang1 =  elgg_echo('liang:lee:account:activate:2');
$lang2 = elgg_echo('liang:lee:account:activation:3');

$html = <<<HTML
<div class="leeaccountactivate-activate">
      <div class="inner">
                  <h3> $lang1 </h3><br />
				  <p>$lang2</p><br/>
				    $user
                    $submit
</div>
</div>
HTML;
echo $html;
?>