<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
 
elgg_register_event_handler('init', 'system', 'LiangLeeAccountDeactivate');

require_once(LiangLee_plugin_path(
								  'LiangLeeAccountDeactivate',
								  'classes').
			                      'LiangLeeAccountDeactivate.php'
								  );
/**
 * Intitlize a LiangLeeAccountDeactivate
 * @return return;
 */
function LiangLeeAccountDeactivate(){
	
         elgg_register_page_handler('account', 'LiangLeeAccountDeactivate_view');
		 
		 $actions = new LiangLeePath;
		 elgg_extend_view('css/elgg', 'LeeActivateAccount/css');
		 elgg_unregister_action('login');
		 elgg_register_action('account/sendactivation', 
							  $actions->action('LiangLeeAccountDeactivate') . 'sendactivation.php',
							  'public'
							  );
		 elgg_register_action('login', 
							  $actions->action('LiangLeeAccountDeactivate') . 'login.php',
							  'public'
							  );
		elgg_register_action('account/deactivate', 
							  $actions->action('LiangLeeAccountDeactivate') . 'deactivate.php'
							  );

    	elgg_register_event_handler('pagesetup', 
									'system', 
									'LiangLeeAccountDeactivate_Pagesetup'
									);
}
/**
 * Register a pages for Liang Lee Account Deactivate
 * account/activate/
 * account/activation/conformation/<code>/<username>
 * account/deactivated
 *
 * @arg $page  switch
 *
 * @return bool;
 */
function LiangLeeAccountDeactivate_view($page) {
$base_dir = lee_wwwmod . 'LiangLeeAccountDeactivate/pages/LiangLeeAccountDeactivate';
if (!isset($page[0])) {
	 return false;
}
switch ($page[0]) {
		case "activate":
		if (isset($page[1])
						&& isset($page[2])) {
				set_input('user', $page[2]);
                set_input('code', $page[1]);
		} 
			include "$base_dir/activate.php";	
			break;
	    
		case "deactivated":
			include "$base_dir/deactivated.php";
			break;
			
		case "activation":
		if(isset($page[1])){
	         set_input('actvation', $page[1]);
             set_input('user', $page[2]);
		}
			include "$base_dir/activation.php";
			break;
					
		default:
			return false;
	}
	return true;
}
/**
 * Setup  a settings page menu item
 * @return menu;
 */
function LiangLeeAccountDeactivate_Pagesetup(){
$user = elgg_get_logged_in_user_guid();	
if (elgg_get_context() == "settings" && $user) {

$params =  array(
	    		'name' => 'lianglee:account:activate',
		    	'href' => "action/account/deactivate?user={$user}",
			    'text' => elgg_echo('liang:lee:account:deactivate'),
			    'is_action' => TRUE,
			    'priority' => 1000,
    			'section' => 'alt',
		);
   elgg_register_menu_item('page', $params);
}

}