<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File activation.php
 */
$activation = get_input('actvation');
$user = get_input('user');

if(empty($user) 
		 && empty($activation)){
               echo elgg_echo('liang:lee:account:activation:4');
}

if(isset($activation) 
		 && $activation == 'conformation' 
		 && !empty($user)){

           echo elgg_view_form('lee/sendactivation', array(
					                       'action' => 'action/account/sendactivation'
			));

}