<?php 
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File activate.php
 */
lee_set_ajax_submit(array(
						  'form_id' => '#account_activate', 
						  'process_id' => '#wait',
						  'type' => 'post',
						  ));
echo elgg_view_form('lee/accountactivate', array(
					                       'action' => LiangLee_AccountDeactivate::action(),
										   'id' => "account_activate"
			
			));

?>
