<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File css.php
 */
?>

.leeaccountactivate-activate{
margin-left: 200px;
margin-right: 200px;
border-right: 3px solid #ccc;	
border-bottom: 3px solid #ccc;	
border-top: 1px solid #ccc;	
border-left: 1px solid #ccc;	
margin-top: 20px;
}
.leeaccountactivate-activate .inner{
padding: 20px;
background-color: rgb(252, 252, 252);
}
.leeaccountactivate-activate-message-sucess {
margin-top: 20px;
margin-left: 200px;
margin-right: 200px;
margin-left: 200px;
margin-right: 200px;
background: rgb(122, 209, 122);
border: 2px solid rgb(74, 145, 91);
}
.leeaccountactivate-activate-message-sucess .inner {
padding: 20px;
color: rgb(74, 145, 91);
font-size: 15px;
font-weight: bold;
}
.leeaccountactivate-activate-message-error {
margin-top: 20px;
margin-left: 200px;
margin-right: 200px;
margin-left: 200px;
margin-right: 200px;
background:#F6CBCA;
border:2px #CB2026 solid;
}
.leeaccountactivate-activate-message-error .inner {
padding: 20px;
color:#CB2026;
font-size: 15px;
font-weight: bold;
}