<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File deactivated.php
 */
$lang1 = elgg_echo("liang:lee:account:activation:5"); 
$lang2 = elgg_echo("liang:lee:account:activation:6");
$url = lee_baseurl.'account/activation';
$html = <<<HTML
	 <div class="leeaccountactivate-activate-message-sucess">
	            <div class="inner">
               $lang1  <a href="{$url}">$lang2</a>
				</div>
	</div>
HTML;
	echo $html;	