<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File en.php
 */
$english = array(
        'liang:lee:account:activate' => 'Activate your account',
		'liang:lee:account:activate:1' => 'Please enter a code that you recieved in email.',
		'liang:lee:account:activate:2' => 'Email me activation',
		'lianglee:activation:email:subject' => 'Activate your account',
		'liang:lee:account:activation' => 'Account activation',
		'liang:lee:account:activation:3' => 'Your account is deactive to active your account press button below',
		'liang:lee:account:deactivate' => 'Deactivate Account',
		'lianglee:activation:email' => 'Hi there,
		 
		 Your activation code is : %s
		 
		 To activate your account click link below:
		 
		  %s
		  
		 The link will be valid for 24 hours only.
		 
		 You can not reply this email.
		 ',
		 'liang:lee:account:activation:4' => 'To activate your account please login using your login username and password after that you will redirected to account activation page.',
		 'liang:lee:account:activation:5' => 'Your account is sucessfully deactivated,',
		 'liang:lee:account:activation:6' => 'How to reactivate?',
		 'liang:lee:account:deactivated' => 'Account deacitvated',
		 'liang:lee:account:activation:7' => 'Please check your email, you will recieve a activation code.',
		 'liang:lee:account:activation:8' => 'Cannot send activation code , please try again',
		 'liang:lee:account:activation:success' => 'You account is sucessfully activated.',
         'liang:lee:account:activation:error' => 'You can not activate account at this time, check your code.',

 );
					
add_translation("en", $english);
