<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File activate.php
 */
require_once(dirname(dirname(dirname(dirname(__FILE__)))).'/engine/start.php');
$user = get_input('leeactivateaccount_user');
$code = get_input('leeactivateaccount_code');

if(!elgg_is_xhr()){
	exit;	   
}
$activate = new LiangLee_AccountDeactivate;
$activate->uservalidate($user, TRUE, $code);

$lang1 = elgg_echo('liang:lee:account:activation:success');
$lang2 = elgg_echo('liang:lee:account:activation:error');

if($activate->activate()){
$html = <<<HTML
	 <div class="leeaccountactivate-activate-message-sucess">
	            <div class="inner">
				$lang1
				</div>
	</div>
HTML;
	echo $html;			
}
else {
	$html = <<<HTML
	 <div class="leeaccountactivate-activate-message-error">
	            <div class="inner">
                 $lang2	
				</div>
	</div>
HTML;
	echo $html;	
}

