<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
 
$user = get_input('user');

$deactivate = new LiangLee_AccountDeactivate;
$deactivate->uservalidate($user);

if($deactivate->deactivate()){
     	system_message('Your account is sucessfully deacitvated');
		forward('account/deactivated');
} 
else {
		system_message('You can not deactivate your account');
}