<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File sendactivation.php
 */
$user = get_input('leeactivateaccount_user');
$send = new LiangLee_AccountDeactivate;
if($send->sendactivation($user)){
   system_message(elgg_echo('liang:lee:account:activation:7'));	
}
else {
   register_error(elgg_echo('liang:lee:account:activation:8'));
}