<?php
/**
 * Liang Lee Account Deactivate
 * Allow users to activate or deactivate his/her account like facebook
 * @package LiangLeeAccountDeacitvate
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File deativate.php
 */
 
$content = elgg_view('LeeActivateAccount/deactivated'); 
$title = elgg_echo('liang:lee:account:deactivated');
$params = array(
	'content' =>  $content,
	'title' => $title,
	'sidebar' => false,
	'filter_override' => false
);

$body = elgg_view_layout('one_column', $params);
echo elgg_view_page($title, $body);
